# Generated by Django 5.2 on 2025-05-06 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('floor', models.IntegerField(default=0)),
                ('nightVal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('hourVal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('numCoupleBed', models.IntegerField(default=0)),
                ('numSingleBed', models.IntegerField(default=0)),
                ('bathtub', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('checkIn', models.DateTimeField(default='2025-01-01 00:00:00')),
                ('checkOut', models.DateTimeField(default='2025-01-01 00:00:00')),
                ('guest', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.guest')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
